filetype: git-config

detect:
    filename: "git(config|modules)$|\\.git/config$"

rules:
    - constant.bool.true: "\\b(true)\\b"
    - constant.bool.false: "\\b(false)\\b"
    - identifier: "^[[:space:]]*[^=]*="
    - constant: "^[[:space:]]*\\[.*\\]$"
    - constant: "\"(\\\\.|[^\"])*\"|'(\\\\.|[^'])*'"
    - comment:
        start: "#"
        end: "$"
        rules: []
