filetype: privoxy-config

detect: 
    filename: "privoxy/config$"

rules:
    - statement: "(accept-intercepted-requests|actionsfile|admin-address|allow-cgi-request-crunching|buffer-limit|compression-level|confdir|connection-sharing|debug|default-server-timeout|deny-access|enable(-compression|-edit-actions|-remote-http-toggle|-remote-toggle)|enforce-blocks|filterfile|forward(ed-connect-retries|-socks(4a?|5))?|handle-as-empty-doc-returns-ok|hostname|keep-alive-timeout|listen-address|log(dir|file)|max-client-connections|permit-access|proxy-info-url|single-threaded|socket-timeout|split-large-forms|templdir|toggle|tolerate-pipelining|trust(file|-info-url)|user-manual)[[:space:]]"
    - comment: "(^|[[:space:]])#([^{].*)?$"
    - indent-char.whitespace: "[[:space:]]+$"
    - indent-char: "	+ +| +	+"
